<?php

return [
    'ACTIVATED'                 => 1,
    'UNACTIVATED'               => 0,
    'VERIFICATION_TOKEN_LENGTH' => 60,
    'AVATAR_PATH'               => 'images/avatar/', //'/file/avatar',
    'FILE_MODE'                 => 0777,
    'NO_TIME_LIMIT'             => 0,
    'FOR_RENT_VAL'              => 1,
    'NEED_RENT_VAL'             => 0,
    'POST_PHOTOS_PATH'          => '/images/posts/',
    'FILE_NAME_LIMIT'           => 40,
    'IMG_MAX_HEIGHT'            => 500,
    'IMG_MAX_WIDTH'             => 1000,
    'POST_SLUG_LENGTH_LIMIT'    => 75,
    'URL_SEPARATOR'             => '~',
    'HOURS_A_DAY'               => 24,
    'COMMENTS_PER_PAGE'         => 10,
    'ROLE_MEM'                  => 'Member',
    'ROLE_MOD'                  => 'Mod',
    'ROLE_ADMIN'                => 'Admin',
    'ROLE_WEBMASTER'            => 'Webmaster',
    'HTTP_OK_STATUS'            => 200,
    'HTTP_CREATED_STATUS'       => 201,
    'HTTP_BAD_REQUEST_STATUS'   => 400,
    'POSTS_PER_PAGE'            => 20,
    'HTTP_UNAUTHORIZED'         => 401,
    'HTTP_NOT_FOUND'            => 404,
    'POST_ACCEPT'               => 1,
    'POST_DENY'                 => 0,
    'DATETIME_FORMAT_DB'        => 'Y-m-d H:i:s',
    'TIMEDATE_FORMAT_HUMAN'     => 'H:i:s d/m/Y',
    'DATETIME_FORMAT_HUMAN'     => 'd/m/Y H:i:s',
    'ROLE_MEM_VAL'              => 4,
    'ROLE_MOD_VAL'              => 3,
    'ROLE_ADMIN_VAL'            => 2,
    'ROLE_WEBMASTER_VAL'        => 1,
];
