<?php

return [
    'ACTIVATED'                 => 1,
    'UNACTIVATED'               => 0,
    'VERIFICATION_TOKEN_LENGTH' => 60,
    'AVATAR_PATH'               => 'images/avatar/', //'/file/avatar',
    'FILE_MODE'                 => 0777,
    'NO_TIME_LIMIT'             => 0,
    'FOR_RENT_VAL'              => 1,
    'NEED_RENT_VAL'             => 0,
    'POST_PHOTOS_PATH'          => '/images/posts/',
    'FILE_NAME_LIMIT'           => 40,
    'IMG_MAX_HEIGHT'            => 500,
    'IMG_MAX_WIDTH'             => 1000,
    'POST_SLUG_LENGTH_LIMIT'    => 75,
    'URL_SEPARATOR'             => '~',
    'HOURS_A_DAY'               => 24,
    'COMMENTS_PER_PAGE'         => 10,
    'ROLE_MEM'                  => 'Member',
    'ROLE_MOD'                  => 'Mod',
    'ROLE_ADMIN'                => 'Admin',
    'ROLE_WEBMASTER'            => 'Webmaster',
    'HTTP_OK_STATUS'            => 200,
    'HTTP_CREATED_STATUS'       => 201,
    'HTTP_BAD_REQUEST_STATUS'   => 400,
];
